### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by heaucques** [SheepTester/olamreee#22] opened 2018-10-30 00:46 UTC
dont resolve this pls

**Comment by anematode** [comment] 2018-10-30 02:00
There are a variety of reasons why a student may post on FLEX10: Flex Time La Place (8403 2 Full Year). As I've written before, Schoology is the new frontier in social media uptake. Supporting revolutionary new features like HTML, embedded iframes, and unique tools of digital censorship -- including correcting "dаmn" to "I don't understand" and "w​​​t​​f​" to "I'm frustrated" -- Schoology allows teenagers to further express themselves in ways other platforms cannot contain. To illustrate what I am saying, let us examine a controversial example of this expression.

On Saturday, October 27th, 2018, Gunn student Kevin Jump posted the following:

"Hi frustrated, I’m Dad!" [1]

In this striking passage, Jump alludes to Schoology's autocorrection of "w​​​t​​f" to "I'm frustrated" and combines this concept with a hackneyed joke. Taken literally, Jump implies that the reader's name is "frustrated," and that he is the reader's father. To emphasize his emotion, he ends the post with an exclamation mark. As readers, the juxtaposition of a simple and nonsensical statement with this excitement is entertaining. Furthermore, considering this excitement stems partially from a core feature of Schoology, Jump implies that he takes interest in Schoology as a social media platform to spread his ideas and humor throughout the world.

Not all reactions to Jump's post, however, were so positive. Gunn students wrote comments on the post, calling it "useless" [1] and "nonsense" [1]. This is likely due to the perceived unintended nature of students' ability to post in the Flex Time Schoology class, and the annoyance caused by each post in the form of notifications and taking up space on students' home page. These issues could be considered damaging to students' ability to focus on school work and acquire information from teachers. The distractive power of Schoology as a platform is reminiscent of an ever-growing pattern in social media. According to the BBC,
"A... study conducted in 2016 involving 1,700 people found a threefold risk of depression and anxiety among people who used the most social media platforms. Reasons for this, they suggested, include cyber-bullying, having a distorted view of other people’s lives, and feeling like time spent on social media is a waste." [2]

These problems may be inchoate in the Schoology platform, but mainly due to the platform's infancy. After all, people started posting on Flex Time La Place relatively recently, starting with Sean's post on Wednesday, October 17th. The way that Schoology, the Gunn administration, and Gunn students will deal with the inherent problems of a new social medium, along with its interactions with academics, will be critical in the development and maturation of this platform.

[1] Schoology. “Learning Management System | LMS | Schoology.” Schoology, 2018, https://pausd.schoology.com/course/1887085609/updates.

[2] Brown, Jessica. “Future - Is Social Media Bad for You? The Evidence and the Unknowns.” BBC, BBC, 5 Jan. 2018, www.bbc.com/future/story/20180104-is-social-media-bad-for-you-the-evidence

**Comment by SheepTester** [comment] 2020-05-02 17:19
resolving

**Closed by SheepTester** 2020-05-02 17:19 UTC
Labels: help wanted, invalid, question, wontfix
